name: build
run-name: Build and Test
on: [push]
env:
  APT_DEPENDENCIES: cmake libsfml-dev libx11-dev xorg-dev libudev-dev libvorbis-dev libflac-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y $APT_DEPENDENCIES
      - name: Build
        run: |
          cmake -B build
          cmake --build build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y $APT_DEPENDENCIES
      - name: Test
        run: |
          echo "Tests are disabled for now"
          # make getGTest
          # make getSFML
          # make tests
          # ./tests
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Check Format
        run:
          - clang-format --style=llvm -dump-config > .clang-format
          - echo "END" > .clang-format
          - cat .clang-format
          # ./clang-format.sh
